### ISSUE TITLE
SNAPSHOT currently seems to create two open sessions when logging in?

### ISSUE THREAD

**Issue by danhaywood** [isisaddons/isis-module-sessionlogger#6]
to reproduce (I believe):
- login (only one session active)
- logout
- login again (two sessions active, plus the previous one shown as completed)

**Comment by martin-g** [comment]
I'll debug it tomorrow.

**Comment by danhaywood** [comment]
Must admit that it was Jeroen who discovered this, but I haven't double checked.  I just didn't want to lose the issue in case it is real.

**Comment by martin-g** [comment]
Carlos reported similar issue as well.

**Comment by martin-g** [comment]
Just tested the scenario and it is not reproducible here :-/

**Comment by danhaywood** [comment]
Issue was with https://issues.apache.org/jira/browse/ISIS-1061 (Wicket 6.19.0 broke us...)
